# Generated by Django 6.0.4 on 2026-05-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category_name",
            field=models.ForeignKey(
                help_text="Выберите категорию продукта",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Введите цену за шт.", max_digits=10, verbose_name="Цена за покупку"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание продукта"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=150, verbose_name="Наименование продукта"),
        ),
    ]
