# Generated by Django 6.0.4 on 2026-05-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Опубликовать продукт в каталоге", verbose_name="Опубликовано"
            ),
        ),
    ]
