# 1. Указываем имя пайплайна
name: Web Store Project Deploy

# 2. Указываем, при каких событиях запускается пайплайн
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# 3. Создание jobs:
jobs:
  # Проверка кода линтером:
  lint:
    runs-on: ubuntu-latest
    # Прописываем шаги для job:
    steps:
      # Шаг 1. Скачиваем актуальный код репозитория:
      - name: Check out code
        uses: actions/checkout@v6
      # Шаг 2. Устанавливаем нужную версию Python:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      # Шаг 3. Устанавливаем Poetry:
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.2.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      # Шаг 4. Устанавливаем линтер flake8:
      - name: Install Lint Tools
        run: poetry install --no-root && poetry run pip install flake8
      # Шаг 5. Запускаем линтер Flake8 для всех python-файлов в проекте:
      - name: Run Flake8
        run: poetry run flake8 . --ignore=E501,F401 # Пропускаем длинные строки и неиспользуемые импорты для тестов

  # Запуск тестов
  test:
    # Запуск тестов только после успешного прохождения линтера:
    needs: lint
    runs-on: ubuntu-latest
    # Прописываем шаги для job:
    steps:
      # Шаг 1. Скачиваем актуальный код репозитория:
      - name: Check out code
        uses: actions/checkout@v6
      # Шаг 2. Устанавливаем нужную версию Python:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      # Шаг 3. Устанавливаем Poetry:
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.2.1
      # Шаг 4. Устанавливаем зависимости:
      - name: Install dependencies
        run: poetry install --no-root
      # Шаг 5. Подменяем Postgres на тестовый SQLite
      - name: Run tests with SQLite
        env:
          DEBUG: "True"
          SECRET_KEY: "ci-test-secret-key-12345"
          DB_NAME: "test_db"
          DB_USER: "postgres"
          DB_PASSWORD: "password"
          DB_HOST: "localhost"
          DB_PORT: "5432"
          DJ_TEST_USE_SQLITE: "True"
        run: poetry run python manage.py test

  # Деплой на сервер с помощью Docker:
  deploy:
    needs: test # Запускаем деплой только после прохождения тестов
    if: github.event_name == 'push' # пул-реквесты сторонних пользователей не могут запускать деплой
    runs-on: ubuntu-latest

    steps:
      # Деплой на сервере Yandex Cloud через SSH-соединение:
      - name: Deploy to Yandex Cloud Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Переходим в директорию проекта на сервере Яндекса:
            cd ${{ secrets.DEPLOY_DIR }}
            
            # Скачиваем обновленный код из ветки main:
            git pull origin main
            
            # Перезапускаем всю связку контейнеров (Django, Nginx, Postgres, Redis):
            sudo docker compose up -d --build
            
            # Применяем миграции внутри контейнера:
            sudo docker compose exec -T web poetry run python manage.py migrate
